### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by PhongTong** [MikeMoolenaar/Migaku-Japanese-Addon-Updated#2]
**Environment**
  - OS: [ Windows 10 ]
  - Anki version: [ Anki 2.1.54 (b6a7760c)⁩]

**Description**  
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-17 20:05:31

Caught exception:
Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 197, in on_window_init
  File "aqt.main", line 243, in setupProfileAfterWebviewsLoaded
  File "aqt.main", line 290, in setupProfile
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 84, in repl
  File "aqt.main", line 470, in loadProfile
  File "aqt.hooks_gen", line 3250, in __call__
  File "anki.hooks", line 34, in runHook
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons21\Migaku-Japanese-Addon-Updated\autoCSSJSHandling.py", line 92, in injectWrapperElements
    self.mw.col.models.save(model)
  File "anki.models", line 559, in save
  File "anki.models", line 542, in update
  File "anki._backend.generated", line 861, in add_or_update_notetype
  File "anki._backend", line 146, in _run_command
anki.errors.CardTypeError: Mẫu thẻ số ⁨2⁩ trong phiếu loại '⁨2. Picture Words⁩' gặp sự cố.<br>Mặt trước giống mẫu thẻ ⁨1⁩

**Comment by MikeMoolenaar** [comment]
This  indicates there is an error in one of your note types. It does mention which note type this is exactly in Anki 2.1.66 so please update and check the template. This is not an error with this addon as discussed in #5.
